---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Add fail2ban jail configuration file
  copy:
    src: etc_fail2ban_jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
